# Generated by Django 2.2 on 2020-08-05 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20200805_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='status',
            field=models.CharField(choices=[('New', 'Новая'), ('In_progress', 'В процессе'), ('Done', 'Сделано')], default='New', max_length=300, verbose_name='Статус'),
        ),
    ]
