# Generated by Django 2.2 on 2020-08-05 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_auto_20200806_0014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuetracker',
            name='type',
            field=models.ForeignKey(default='Task', on_delete=django.db.models.deletion.PROTECT, related_name='type', to='webapp.Type', verbose_name='Тип'),
        ),
    ]
