# Generated by Django 2.2 on 2020-08-07 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_auto_20200807_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='status',
            field=models.CharField(choices=[('New', 'Новая'), ('In_progress', 'В процессе'), ('Done', 'Сделано')], default='New', max_length=300, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='type',
            name='name',
            field=models.CharField(choices=[('Task', 'Задача'), ('Bug', 'Ошибка'), ('Enhancement', 'Улучшение')], default='Task', max_length=300, verbose_name='Тип'),
        ),
    ]
