# Generated by Django 2.2 on 2020-08-09 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_auto_20200807_2123'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issuetracker',
            old_name='type',
            new_name='type_old',
        ),
    ]
