# Generated by Django 2.2 on 2020-08-09 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_auto_20200809_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuetracker',
            name='type',
            field=models.ManyToManyField(related_name='type', to='webapp.Type', verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='issuetracker',
            name='type_old',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='type_set', to='webapp.Type', verbose_name='Тип'),
        ),
    ]
