# Generated by Django 2.2 on 2020-08-09 05:52

from django.db import migrations

def transfer_tags(apps, schema_editor):
    Issue = apps.get_model('webapp.IssueTracker')
    for task in Issue.objects.all():
        task.type.add(task.type_old)

def rollback_transfer(apps, schema_editor):
    Issue = apps.get_model('webapp.IssueTracker')
    for task in Issue.objects.all():
        task.type_old.add(task.type)


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0010_auto_20200809_1149'),
    ]

    operations = [
        migrations.RunPython(transfer_tags, rollback_transfer)
    ]
