# Generated by Django 2.2 on 2020-08-12 18:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0012_remove_issuetracker_type_old'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuetracker',
            name='summary',
            field=models.CharField(default='None description', max_length=300, validators=[django.core.validators.MinLengthValidator(10)], verbose_name='Задание'),
        ),
    ]
