# Generated by Django 2.2 on 2020-08-12 19:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0017_auto_20200813_0113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuetracker',
            name='description',
            field=models.TextField(blank=True, default='None description', max_length=3500, null=True, validators=[django.core.validators.ProhibitNullCharactersValidator(0)], verbose_name='Описание'),
        ),
    ]
