# Generated by Django 2.2 on 2020-08-12 19:25

import django.core.validators
from django.db import migrations, models
import webapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0021_auto_20200813_0123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuetracker',
            name='summary',
            field=models.CharField(default='None description', max_length=300, validators=[django.core.validators.MinLengthValidator(10), webapp.models.is_title], verbose_name='Задание'),
        ),
    ]
