# Generated by Django 2.2 on 2020-08-12 19:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0029_auto_20200813_0145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuetracker',
            name='description',
            field=models.TextField(default='None description', max_length=3500, validators=[django.core.validators.ProhibitNullCharactersValidator], verbose_name='Описание'),
        ),
    ]
