# Generated by Django 2.2 on 2020-08-13 11:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0032_auto_20200813_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuetracker',
            name='description',
            field=models.TextField(max_length=3500, null=True, validators=[django.core.validators.ProhibitNullCharactersValidator], verbose_name='Описание'),
        ),
    ]
