# Generated by Django 2.2 on 2020-08-13 11:20

from django.db import migrations, models
import webapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0033_auto_20200813_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuetracker',
            name='description',
            field=models.TextField(default='None description', max_length=3500, null=True, validators=[webapp.models.is_null], verbose_name='Описание'),
        ),
    ]
