# Generated by Django 2.2 on 2020-08-13 12:24

from django.db import migrations, models
import webapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0034_auto_20200813_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuetracker',
            name='description',
            field=models.TextField(blank=True, default='None description', max_length=3500, null=True, validators=[webapp.models.is_null], verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='issuetracker',
            name='summary',
            field=models.CharField(default='None', max_length=300, validators=[webapp.models.is_title], verbose_name='Задание'),
        ),
    ]
