# Generated by Django 2.2 on 2020-08-15 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0035_auto_20200813_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuetracker',
            name='update_time',
            field=models.DateTimeField(auto_now=True, verbose_name='Время обновления'),
        ),
    ]
