# Generated by Django 2.2 on 2020-08-15 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0036_issuetracker_update_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issuetracker',
            old_name='update_time',
            new_name='update_at',
        ),
    ]
