# Generated by Django 2.2 on 2020-08-15 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0038_auto_20200815_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type',
            name='name',
            field=models.CharField(choices=[('Task', 'Задача'), ('Bug', 'Ошибка'), ('Enhancement', 'Улучшение')], default='Task', max_length=300, verbose_name='Тип'),
        ),
    ]
