# Generated by Django 2.2 on 2020-08-22 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0039_auto_20200815_2152'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='None', max_length=50, verbose_name='Название')),
                ('description', models.TextField(default='None', max_length=300, verbose_name='Описание')),
                ('starts_date', models.DateField(verbose_name='дата начала')),
                ('finish_date', models.DateField(blank=True, null=True, verbose_name='дата начала')),
            ],
        ),
    ]
