# Generated by Django 2.2 on 2020-09-10 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0044_project_users'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'permissions': [('webapp.change_users', 'Может редактировать пользователей в проекте')], 'verbose_name': 'Проект', 'verbose_name_plural': 'Проекты'},
        ),
    ]
